server {
    listen 80;
    server_name _;

    root /var/www/html/src;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index info.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /api/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /phpmyadmin {
        auth_basic "Acesso Restrito";
        auth_basic_user_file /etc/nginx/.htpasswd;

        alias /var/www/html/;
        index index.php;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass phpmyadmin:9000;
            fastcgi_param SCRIPT_FILENAME $request_filename;
        }
    }

    location ^~ /grafana {

        proxy_pass http://grafana:3000;
        
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
